ECommerce.Web/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ECommerce.Web.Models
{
    public class Order
    {
        public int Id { get; set; }
        [Required]
        public int CustomerId { get; set; }
        [Required]
        public DateTime OrderDate { get; set; }
        [Required]
        public DateTime CreatedOn { get; set; }
        [Required]
        public string OrderName { get; set; }

        [Required]
        public double Amount { get; set; }
        [Required]
        public bool DeliveryStatus { get; set; }

        [ForeignKey("CustomerId")]
        public virtual Customer Customer { get; set; }
    }
}

ECommerce.Web/Controllers/CustomerController.cs
using ECommerce.Web.App_Start;
using ECommerce.Web.Managers;
using ECommerce.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECommerce.Web.Controllers
{
    [Authorize]
    public class CustomerController : BaseController
    {

        private ICustomerManager _customerManager;

        //git test


        public CustomerController(ICustomerManager _customerManager)
        {

            this._customerManager = _customerManager;
        }
        
        public ActionResult Index(string currentFilter, string searchString, int? page = 1, int? NoOfRows = 10)
        {
            
            if (page < 1)
            {
                page = 1;
            }

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.page = page;
            ViewBag.CurrentFilter = searchString;
            ViewBag.NoOfRows = NoOfRows;
            return View(_customerManager.GetCustomerPageList(page.Value, NoOfRows.Value,  searchString));

        }

        // GET: Users/Create
        public ActionResult Create()
        {
            try
            {
                Customer model = new Customer();
                model.Id = 0;
                return View(model);
            }
            catch (Exception ex)
            {
                this.error(ex.Message.ToString());
                return RedirectToAction("Index");
            }

        }

    

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Customer customer)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (_customerManager.CheckIfExist(customer.PhoneNo))
                    {
                        this.error("Customer with Phone Number <b> '" + customer.PhoneNo + "'</b> alresdy exists.");
                        return View(customer);
                    }
                    _customerManager.Add(customer);
                    _customerManager.Save();
                    this.save();
                    return RedirectToAction("Index");
                }
                return View(customer);
            }
            catch (Exception ex)
            {
                this.error(ex.Message.ToString());
                return RedirectToAction("Index");
            }

        }
     
        public ActionResult Edit(int? id)
        {
            if (id == 0)
            {
                this.error("Invalid try...");
                return RedirectToAction("Index");
            }
            Customer customer = _customerManager.GetById(id.Value);
            if (customer != null)
            {
                return View(customer);

            }
            else
            {
                this.error("Invalid try...");
                return RedirectToAction("Index");
            }

        }

        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Customer customer)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (_customerManager.CheckIfExistForUpdate(customer.Id, customer.PhoneNo))
                    {
                        this.error("Customer with Phone Number <b> '" + customer.PhoneNo + "'</b> alresdy exists.");
                        return View(customer);
                    }
                    _customerManager.Update(customer);
                    _customerManager.Save();
                    this.update();
                    return RedirectToAction("Index");
                }
                return View(customer);
            }
            catch (Exception ex)
            {
                this.error(ex.Message.ToString());
                return RedirectToAction("Index");
            }
        }

  
        public ActionResult Delete(int? id)
        {

            if (id == 0)
            {
                this.error("Invalid try...");
                return RedirectToAction("Index");
            }
            Customer customer = _customerManager.GetById(id.Value);
            if (customer != null)
            {
                _customerManager.Delete(customer);
                _customerManager.Save();
                this.delete();
                return RedirectToAction("Index");
            }
            else
            {
                this.error("Invalid try...");
                return RedirectToAction("Index");
            }
        }

        
        public ActionResult Details(int? id)
        {
            if (id == 0)
            {
                this.error("Invalid try...");
                return RedirectToAction("Index");
            }
            Customer customer = _customerManager.GetById(id.Value);
            if (customer != null)
            {
                return View(customer);
            }
            else
            {
                this.error("Invalid try...");
                return RedirectToAction("Index");
            }
        }
    }
}

ECommerce.Web/Controllers/OrderController.cs
using ECommerce.Web.App_Start;
using ECommerce.Web.Managers;
using ECommerce.Web.Models;
using ECommerce.Web.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECommerce.Web.Controllers
{
    [Authorize]
    public class OrderController : BaseController
    {

        private ICustomerManager _customerManager;
        private IOrderManager _ordeManager;


        public OrderController(ICustomerManager _customerManager, IOrderManager _ordeManager)
        {

            this._customerManager = _customerManager;
            this._ordeManager = _ordeManager;
        }
        
        public ActionResult Index(string currentFilter, string searchString, string customerName, int? page = 1, int? NoOfRows = 10)
        {
            
            if (page < 1)
            {
                page = 1;
            }

            if (searchString != null )
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            
            ViewBag.page = page;
            ViewBag.CurrentFilter = searchString;
            ViewBag.customerName = customerName;
            ViewBag.NoOfRows = NoOfRows;
            return View(_ordeManager.GetOrderPageList(page.Value, NoOfRows.Value,  searchString, customerName));

        }

        // GET: Users/Create
        public ActionResult Create()
        {
            try
            {
                Order model = new Order();
                model.Id = 0;
                model.OrderDate = DateTime.Now;
                ViewBag.CustomerId = new SelectList(_customerManager.GetCustomerDropDown(), "Id", "Name");
                return View(model);
            }
            catch (Exception ex)
            {
                this.error(ex.Message.ToString());
                return RedirectToAction("Index");
            }

        }

    

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Order order)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //Customer customer=_customerManager.GetById(order.CustomerId);
                    //order.OrderName = customer.Name+"-"+order.OrderName + "-" + order.OrderDate.ToShortDateString();
                    order.CreatedOn = DateTime.Now;
                    _ordeManager.Add(order);
                    _ordeManager.Save();
                    this.save();
                    return RedirectToAction("Index");
                }
                ViewBag.CustomerId = new SelectList(_customerManager.GetCustomerDropDown(), "Id", "Name", order.CustomerId);
                return View(order);
            }
            catch (Exception ex)
            {
                this.error(ex.Message.ToString());
                return RedirectToAction("Index");
            }

        }
     
        public ActionResult Edit(int? id)
        {
            if (id == 0)
            {
                this.error("Invalid try...");
                return RedirectToAction("Index");
            }
            Order order = _ordeManager.GetById(id.Value);
            if (order != null)
            {
                ViewBag.CustomerId = new SelectList(_customerManager.GetCustomerDropDown(), "Id", "Name", order.CustomerId);
                return View(order);

            }
            else
            {
                this.error("Invalid try...");
                return RedirectToAction("Index");
            }

        }

        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Order order)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //if (_ordeManager.CheckIfExistForUpdate(order.Id, order.OrderName))
                    //{
                    //    this.error("Customer with Phone Number <b> '" + order.PhoneNo + "'</b> alresdy exists.");
                    //    return View(order);
                    //}
                    //Customer customer = _customerManager.GetById(order.CustomerId);
                    //order.OrderName = customer.Name + "-" + order.OrderName + "-" + order.OrderDate.ToShortDateString();
                    //order.CreatedOn = DateTime.Now;
                    _ordeManager.Update(order);
                    _ordeManager.Save();
                    this.update();
                    return RedirectToAction("Index");
                }
                ViewBag.CustomerId = new SelectList(_customerManager.GetCustomerDropDown(), "Id", "Name", order.CustomerId); ViewBag.CustomerId = new SelectList(_customerManager.GetCustomerDropDown(), "Id", "Name", order.CustomerId);
                return View(order);
            }
            catch (Exception ex)
            {
                this.error(ex.Message.ToString());
                return RedirectToAction("Index");
            }
        }

  
        public ActionResult Delete(int? id)
        {

            if (id == 0)
            {
                this.error("Invalid try...");
                return RedirectToAction("Index");
            }
            Order order = _ordeManager.GetById(id.Value);
            if (order != null)
            {
                _ordeManager.Delete(order);
                _ordeManager.Save();
                this.delete();
                return RedirectToAction("Index");
            }
            else
            {
                this.error("Invalid try...");
                return RedirectToAction("Index");
            }
        }

        
        public ActionResult Details(int? id)
        {
            if (id == 0)
            {
                this.error("Invalid try...");
                return RedirectToAction("Index");
            }
            Order order = _ordeManager.GetById(id.Value);
            if (order != null)
            {
                return View(order);
            }
            else
            {
                this.error("Invalid try...");
                return RedirectToAction("Index");
            }
        }


        public ActionResult AddCustomer()
        {
            Customer model = new Customer();
            model.Id = 0;
            return PartialView("_addCustomer", model);
        }
        [HttpPost]
        public ActionResult SaveCustomer(Customer customer)
        {
            vmStatus status = new vmStatus();
            try
            {
                
                if (ModelState.IsValid)
                {
                    
                    if (_customerManager.CheckIfExist(customer.PhoneNo))
                    {
                        status.Status = "200";
                        status.Msg = "Customer with Phone Number <b> '" + customer.PhoneNo + "'</b> alresdy exists.";
                        return Json(status, JsonRequestBehavior.AllowGet);
                    }
                    _customerManager.Add(customer);
                    _customerManager.Save();
                    status.Status = "400";
                    status.Msg = "Customer Added Successfull;";
                    return Json(status, JsonRequestBehavior.AllowGet);
                }
                status.Status = "200";
                status.Msg = "Please provide valid input for all required field";
                return Json(status, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                status.Status = "200";
                status.Msg = "Operation Failed";
                return Json(status, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetCustomers()
        {
            var customers=_customerManager.GetCustomerDropDown();
            return Json(customers, JsonRequestBehavior.AllowGet);
        }
    }
}

ECommerce.Web/Views/Order/Create.cshtml
@model ECommerce.Web.Models.Order

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .txtRequired {
        border-left: 2px solid #ff0000;
    }

    .spnRequired {
        color: #ff0000;
    }

    .select2 {
        width: 100% !important;
    }
</style>

<!-- Content Header (Page header) -->
<section class="content-header" style="background-color: #ecf0f5;">
    <ol class="breadcrumb" style="float:left">
        <li><a href="#"><i class="fa fa-cog"></i> Sales</a></li>
        <li class="active">Order</li>
    </ol>
</section>
<section class="content-header" style=" margin-bottom:50px; margin-top:50px; position:relative">
    <h1 style="position:absolute; top:0px ; left:16px">Create Order</h1>
    <a style="position:absolute; top:0px ; right:16px" class="btn btn-default" href="@Url.Action("Index", "Order")"><i class="fa fa-reply"></i> Back to list</a>
</section>
<!-- Main content -->
<section class="content">
    <!-- SELECT2 EXAMPLE -->
    <div class="box box-default">

        @using (Html.BeginForm("Create", "Order", FormMethod.Post, new { @class = "form-horizontal form-label-left", @role = "form", autocomplete = "off" }))
        {
            @Html.AntiForgeryToken()
            <!-- /.box-header -->
            <div class="box-body">

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">
                        Name
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.TextBoxFor(model => model.OrderName, new { @class = "form-control col-md-7 col-xs-12 txtRequired", @id = "txtName", @required = "required", @type = "text", @placeholder = "Name" })
                        @Html.ValidationMessageFor(model => model.OrderName, null, new { @class = "spnRequired" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">
                        Customer
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <div class="txtRequired">
                            @Html.DropDownList("CustomerId", null, String.Empty, new { @class = "form-control select2", @id = "ddlCustomerId", @required = "required", @type = "text" })
                        </div>
                        @Html.ValidationMessageFor(model => model.CustomerId, null, new { @class = "spnRequired" })
                    </div>
                    <button type="button" class="btn btn-primary" id="btnAddCustomer"><i class="fa fa-plus-square-o"></i>Add Customer</button>

                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">
                        Order Date
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <div class="txtRequired">
                            @Html.TextBoxFor(model => model.OrderDate, Model.OrderDate == null ? "" : Model.OrderDate.ToString("yyyy/MM/dd"), new { @class = "form-control date", @id = "txOrderDate", @required = "required", @type = "text", @placeholder = "Order date" })
                        </div>
                        @Html.ValidationMessageFor(model => model.OrderDate, null, new { @class = "spnRequired" })

                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">
                        Price
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.TextBoxFor(model => model.Amount, new { @class = "form-control col-md-7 col-xs-12 txtRequired", @id = "txtName", @required = "required", @type = "number", @min = "1", @placeholder = "Order Price" })
                        @Html.ValidationMessageFor(model => model.Amount, null, new { @class = "spnRequired" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">
                        DeliveryStatus
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        
                        <label>@Html.RadioButtonFor(model => model.DeliveryStatus, "true")  Done</label>
                        <label> @Html.RadioButtonFor(model => model.DeliveryStatus, "false")  Pending</label>

                        @Html.ValidationMessageFor(model => model.DeliveryStatus, "", new { @class = "spnRequired" })


                    </div>
                </div>

                <!-- /.row -->
            </div>
            <!-- /.box-body -->
            <div class="box-footer" style="border-top: 1px dotted #e4e0e0;">
                <div style="margin:0 auto; width:200px">
                    <button type="submit" class="btn btn-primary">SAVE</button>
                    <a class="btn btn-default" href="@Url.Action("Index", "Order")">CANCEL</a>
                </div>
            </div>

        }


    </div>
    <!-- /.box -->
    @*Add Customer Modal*@

    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Create Customer</h5>
                    <span id="vldMsg" hidden style="color:red"></span>
                    @*<button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>*@
                </div>
                <div class="modal-body" id="moda-body">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" id="btnSave" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>


</section>


@section Scripts {

    <script>

        $('#btnAddCustomer').on("click", function () {

            $.ajax({
                type: 'GET',
                url: '@Url.Action("AddCustomer")',
                dataType: 'html',
                success: function (result) {
                    debugger;
                    $('#exampleModal .modal-body').html(result);
                    $('#exampleModal #vldMsg').hide();
                    $('#exampleModal').modal('show');
                },
                error: function (ex) {
                    alert('Operation failed!');
                }
            });


        })
        $('#btnSave').on("click", function () {
            var $Formdata = $('#customerForm').serialize();
            debugger;
            $.ajax({
                type: 'POST',
                url: '@Url.Action("SaveCustomer")',
                dataType: 'json',
                data: $Formdata,
                success: function (result) {
                    debugger;
                    if (result.Status === "400") {
                        $('#exampleModal').modal('hide');
                        LoadCustomer();
                    } else {
                        $('#exampleModal #vldMsg').html(result.Msg);
                        $('#exampleModal #vldMsg').show(300);

                    }

                },
                error: function (ex) {
                    alert('Operation failed!');
                }
            });


        })

        function LoadCustomer() {
            $('#ddlCustomerId').empty();
            $("#ddlCustomerId").append("<option value=''></option>");
            $.ajax({
                type: 'GET',
                url: '@Url.Action("GetCustomers")',
                dataType: 'json',
                success: function (customers) {
                    debugger;
                    $.each(customers, function (i, customer) {
                        $("#ddlCustomerId").append('<option value="' + customer.Id + '">' + customer.Name + '</option>');
                    });

                },
                error: function (ex) {
                    alert('Operation failed!');
                }
            });
        }

        $(document).ready(function () {
            MESSENGER();
        });
    </script>
}

ECommerce.Web/Views/Order/Details.cshtml
@model ECommerce.Web.Models.Order
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<style>
    .lblHead {
        background-color: #eaeaea;
        text-align: right;
        font-weight: bold;
        color: #646464;
    }
</style>









<!-- Content Header (Page header) -->
<section class="content-header" style="background-color: #ecf0f5;">
    <ol class="breadcrumb" style="float:left">
        <li><a href="#"><i class="fa fa-cog"></i> Sales</a></li>
        <li class="active">Order</li>
    </ol>
</section>
<section class="content-header" style=" margin-bottom:50px; margin-top:50px; position:relative">
    <h1 style="position:absolute; top:0px ; left:16px;">Order Detail</h1>

    <div class="btn-group box-tools pull-right" role="group" aria-label="Basic example">
        <a type="button" class="btn btn-default" href="@Url.Action("Index", "Order")"><i class="fa fa-reply"></i> Back to list</a>
        <a type="button" class="btn btn-default" href="@Url.Action("Edit", "Order", new { id=Model.Id})"><i class="fa fa-edit"></i> Edit</a>
    </div>

</section>

<!-- Main content -->
<section class="content">
    <div class="row">

        <!-- /.col -->
        <div class="col-xs-12">
            <div class="box box-primary">
                @*<div class="box-tools pull-right" style="padding: 10px; background-color: #3c8dbc2e">
                    <h4 class="box-title">
                        @Model.Name
                    </h4>
                </div>*@
                <!-- /.box-header -->
                <div class="box-body no-padding">
                    <!-- /.mailbox-read-info -->
                    <!-- /.mailbox-controls -->
                    <div class="mailbox-read-message">
                        <table class="table table-info" style="max-width:500px; margin:0 auto;">
                            <tr>
                                <td class="lblHead">Order Name</td>
                                <td>@Model.OrderName</td>
                            </tr>
                            <tr>
                                <td class="lblHead">Order Date</td>
                                <td>@Model.OrderDate.ToString("dd-MMM-yyyy")</td>
                            </tr>
                            <tr>
                                <td class="lblHead">Customer Name</td>
                                <td>@Model.Customer.Name</td>
                            </tr>
                            
                            <tr>
                                <td class="lblHead">Customer Phone</td>
                                <td>@Model.Customer.PhoneNo</td>
                            </tr>
                            <tr>
                                <td class="lblHead">Order Price</td>
                                <td>@Model.Amount</td>
                            </tr>
                            <tr>
                                <td class="lblHead">Delivery Status</td>
                                @if (Model.DeliveryStatus)
                                {
                                    <td>Done</td>
                                }
                                else
                                {
                                    <td>Pending</td>
                                }
                            </tr>

                        </table>

                    </div>
                    <!-- /.mailbox-read-message -->
                </div>

            </div>
            <!-- /. box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->
@section Scripts {
    <script type="text/javascript">
        MESSENGER();
    </script>
}

ECommerce.Web/Views/Order/_addCustomer.cshtml
@model ECommerce.Web.Models.Customer

@using (Html.BeginForm("Create", "Customer", FormMethod.Post, new { @class = "form-horizontal form-label-left",@id="customerForm", @role = "form", autocomplete = "off" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PhoneNo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PhoneNo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PhoneNo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>*@
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="MaterialUnit">
                Name
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control col-md-7 col-xs-12 txtRequired", @id = "txtName", @required = "required", @type = "text", @placeholder = "Name" })
                @Html.ValidationMessageFor(model => model.Name, null, new { @class = "spnRequired" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="MaterialUnit">
                Phone
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                @Html.TextBoxFor(model => model.PhoneNo, new { @class = "form-control col-md-7 col-xs-12 txtRequired", @id = "txtPhoneNo", @required = "required", @type = "text", @placeholder = "Phone No" })
                @Html.ValidationMessageFor(model => model.PhoneNo, null, new { @class = "spnRequired" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="MaterialUnit">
                Address
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                @Html.TextAreaFor(model => model.Address, new { @class = "form-control col-md-7 col-xs-12 ", @id = "txtName", @type = "text", @placeholder = "Address" })
                @Html.ValidationMessageFor(model => model.Address, null, new { @class = "" })
            </div>
        </div>
        <div class="form-group">
            
        </div>



    </div>
}

<script>
    $(function () {
        $('subscribe-email-form').on('submit', function (e) {
            e.preventDefault();
            $.ajax({
                url: "/notifications/subscribe/",
                type: "POST",
                data: $("subscribe-email-form").serialize(),
                success: function (data) {
                    alert("Successfully submitted.")
                }
            });
        });
    });

    
</script>